#!/bin/bash

export BASE=$(pwd)
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.36.3
export npm_config_arch=x64
export npm_config_runtime=electron
export HOME=~/.electron-gyp

function rebuild-module {
  cd $2
  HOME=~/.electron-gyp node-gyp rebuild \
    --target=$npm_config_target \
    --arch=$npm_config_arch \
    --dist-url=$npm_config_disturl \
    --module_name=$1 \
    --module_path=$2
}

function npm-install() {
  HOME=~/.electron-gyp npm install "$@"
}

function install-deps() {
  echo "Installing dependent modules"
  ## Install dependent modules
  mkdir -p deps
  cd deps

  git clone https://github.com/mapnik/node-mapnik.git
  (cd node-mapnik && git pull && git submodule update --init && make)

  git clone ~/Development/Repositories/Attitude.git
  git clone ~/Development/Repositories/subdivide.git

  git clone https://github.com/davenquinn/gis-core.git
  ln -s $(pwd) ../../node_modules/gis-core
}

if [ ! -d 'deps' ]; then
install-deps
fi

#echo "Installing mapnik"
#npm-install mapnik --build-from-source
(cd deps/Attitude && pip install -e . && npm link)
(cd deps/node-mapnik && git submodule update --init && npm install && npm link)
npm link mapnik
(cd deps/gis-core && npm link mapnik && npm link)

pip install -e deps/subdivide

echo "Installing main application"
pwd
pip install -e .

#DIR=node_modules/mapnik/lib/binding
#cp -r "$DIR/electron-v0.36-darwin-x64" "$DIR/node-v47-darwin-x64"

npm install
npm link attitude
npm link gis-core
