#!/bin/bash

export BASE=$(pwd)
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=1.4.2
export npm_config_arch=x64
export npm_config_runtime=electron
export npm_config_build_from_source=true
#export HOME=~/.electron-gyp

function rebuild-module {
  cd $2
  HOME=~/.electron-gyp node-gyp rebuild \
    --target=$npm_config_target \
    --arch=$npm_config_arch \
    --dist-url=$npm_config_disturl \
    --module_name=$1 \
    --module_path=$2
}

function npm-install() {
  HOME=~/.electron-gyp npm install "$@"
}

function install-deps() {
  echo "Installing dependent modules"
  ## Install dependent modules
  mkdir -p deps
  cd deps

  git clone https://github.com/mapnik/node-mapnik.git
  (cd node-mapnik && git pull && git submodule update --init && make)

  git clone ~/Development/Repositories/Attitude.git
  git clone ~/Development/Repositories/subdivide.git

  git clone https://github.com/davenquinn/gis-core.git
  ln -s $(pwd) ../../node_modules/gis-core
}

if [ ! -d 'deps' ]; then
install-deps
fi

#echo "Installing mapnik"
(cd deps/Attitude && pip install -e . )

dn="deps/node-mapnik"
if [ ! -e "$dn/lib/binding/electron-v1.4-darwin-x64" ]; then
  echo "Building mapnik for electron"
  (cd "$dn" && git submodule update --init && HOME=~/.electron-gyp npm install --build-from-source)
fi

$(npm bin)/linklocal

pip install -e deps/subdivide

echo "Installing main application"
pip install -e .

HOME=~/.electron-gyp npm install
npm link attitude
npm link gis-core
