#!/usr/bin/env bash -e

user=davenquinn
image=ghcr.io/$user/orienteer/orienteer-frontend
version=$(cat package.json | jq -r '.version') 

branch=$(git rev-parse --abbrev-ref HEAD)
tags="-t $image:$version -t $image:$branch"

if [ $branch = "main" ]; then
  tags="$tags -t $image:latest"
fi

docker build -f Dockerfile.frontend $tags .

if [ $1 == "--no-push" ]; then
  exit 0
fi

GITHUB_ACCESS_TOKEN=$(security find-generic-password -w -s "GitHub access token")
echo $GITHUB_ACCESS_TOKEN | docker login ghcr.io -u $user --password-stdin

echo "Pushing images"
docker push $image:$version
docker push $image:$branch

if [ $branch = "master" ]; then
  docker push $image:latest
fi
